### PR TITLE
add comments for tagging update handlers

### PR DESCRIPTION
**Pull request by michaelglass**
added some comments with @jmjr to help us understand the example. Maybe they'll be helpful for others.

great package!

### CODE REVIEW

**Comment by inkuzmin** [comment]
Wow! Thank you so much for your pull requests, they look amazing!

**Comment by inkuzmin** [comment]
I'll try to release the new version with the fixes and improvements you've contributed asap.

**Comment by michaelglass** [comment]
any news?

**Comment by inkuzmin** [comment]
@michaelglass, sorry for the delay! It should be released now.

**Comment by michaelglass** [comment]
you're the best!

**Pull request merged**
